# Generated by Django 5.0.2 on 2024-10-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='six_digit_link',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
