# Generated by Django 5.0.2 on 2024-10-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_alter_competition_six_digit_link'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='competition',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task'),
        ),
    ]
