# Generated by Django 5.0.2 on 2024-10-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_competition_difficulty_competition_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
