# Generated by Django 5.0.2 on 2024-10-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_delete_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='duration',
        ),
        migrations.AddField(
            model_name='competition',
            name='duration_minutes',
            field=models.IntegerField(choices=[(1, '1 minute'), (5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default='30'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
