# Generated by Django 5.0.2 on 2024-10-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_remove_competition_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='duration_minutes',
            field=models.IntegerField(choices=[(1, '1 minute'), (5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=30),
        ),
    ]
