# Generated by Django 5.0.2 on 2024-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description provided by the author.'),
        ),
    ]
