# Generated by Django 5.0.2 on 2024-10-21 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
